application: play-quattro
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /assets
  static_dir: assets
  
- url: /favicon.ico
  static_files: assets/img/favicon.ico
  upload: assets/img/favicon.ico
  
- url: /index\.html
  static_dir: quattrogame.app
  
- url: .*
  script: quattrogame.app

libraries:
- name: webapp2
  version: "2.5.2"
  
- name: jinja2
  version: "2.6"
